=== Kyoril/mmo-data/Interface/GlueUI/Ui.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://mmo-dev.net/ui"
    elementFormDefault="qualified"
    xmlns="http://mmo-dev.net/ui"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="FrameRendererType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="DefaultRenderer" />
      <xs:enumeration value="ButtonRenderer" />
      <xs:enumeration value="CheckboxRenderer" />
      <xs:enumeration value="TextFieldRenderer" />
      <xs:enumeration value="ModelRenderer" />
      <xs:enumeration value="WorldRenderer" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="AnchorPointType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="LEFT" />
      <xs:enumeration value="TOP" />
      <xs:enumeration value="RIGHT" />
      <xs:enumeration value="BOTTOM" />
      <xs:enumeration value="H_CENTER" />
      <xs:enumeration value="V_CENTER" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TilingType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="NONE" />
      <xs:enumeration value="HORZ" />
      <xs:enumeration value="VERT" />
      <xs:enumeration value="BOTH" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="HorzAlignType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="LEFT" />
      <xs:enumeration value="CENTER" />
      <xs:enumeration value="RIGHT" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="VertAlignType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="TOP" />
      <xs:enumeration value="CENTER" />
      <xs:enumeration value="BOTTOM" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="ScriptFileType">
    <xs:attribute name="file" use="required" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="ScriptBlockType">
    <xs:simpleContent>
      <xs:extension base="xs:string" />
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="FontType">
    <xs:attribute name="name" use="required" type="xs:string" />
    <xs:attribute name="file" use="required" type="xs:string" />
    <xs:attribute name="size" use="required" type="xs:decimal" />
    <xs:attribute name="outline" use="optional" type="xs:decimal" />
    <xs:attribute name="shadowX" use="optional" type="xs:decimal" />
    <xs:attribute name="shadowY" use="optional" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="PropertyType">
    <xs:attribute name="name" use="required" type="xs:string" />
    <xs:attribute name="value" use="optional" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="PropertyValueType">
    <xs:attribute name="property" use="required" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="InsetType">
    <xs:attribute name="all" use="optional" type="xs:decimal" />
    <xs:attribute name="left" use="optional" type="xs:decimal" />
    <xs:attribute name="top" use="optional" type="xs:decimal" />
    <xs:attribute name="right" use="optional" type="xs:decimal" />
    <xs:attribute name="bottom" use="optional" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="AreaComponentType">
    <xs:sequence minOccurs="0" maxOccurs="1">
      <xs:element name="Inset" type="InsetType" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="BorderComponentType">
    <xs:sequence minOccurs="0" maxOccurs="1">
      <xs:element name="Area" type="AreaComponentType" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="texture" use="required" type="xs:string" />
    <xs:attribute name="borderSize" use="optional" type="xs:decimal" />
    <xs:attribute name="topSize" use="optional" type="xs:decimal" />
    <xs:attribute name="leftSize" use="optional" type="xs:decimal" />
    <xs:attribute name="rightSize" use="optional" type="xs:decimal" />
    <xs:attribute name="bottomSize" use="optional" type="xs:decimal" />
    <xs:attribute name="tint" use="optional" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="ImageComponentType">
    <xs:sequence minOccurs="0" maxOccurs="2">
      <xs:choice>
        <xs:element name="Area" type="AreaComponentType" minOccurs="0" maxOccurs="1" />
        <xs:element name="PropertyValue" type="PropertyValueType" minOccurs="0" maxOccurs="1" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="texture" use="optional" type="xs:string" />
    <xs:attribute name="tint" use="optional" type="xs:string" />
    <xs:attribute name="tiling" use="optional" type="TilingType" />
  </xs:complexType>

  <xs:complexType name="TextComponentType">
    <xs:sequence minOccurs="0" maxOccurs="1">
      <xs:element name="Area" type="AreaComponentType" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="color" use="optional" type="xs:string" />
    <xs:attribute name="horzAlign" use="optional" type="HorzAlignType" />
    <xs:attribute name="vertAlign" use="optional" type="VertAlignType" />
    <xs:attribute name="wrap" use="optional" type="xs:boolean" />
  </xs:complexType>

  <xs:complexType name="ImagerySectionType">
    <xs:sequence>
      <xs:choice maxOccurs="unbounded">
        <xs:element name="BorderComponent" type="BorderComponentType" />
        <xs:element name="ImageComponent" type="ImageComponentType" />
        <xs:element name="TextComponent" type="TextComponentType" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="name" use="required" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="SectionType">
    <xs:attribute name="section" use="required" type="xs:string" />
    <xs:attribute name="color" use="optional" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="LayerType">
    <xs:sequence>
      <xs:element name="Section" maxOccurs="unbounded" minOccurs="1" type="SectionType" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="StateImageryType">
    <xs:sequence>
      <xs:element name="Layer" type="LayerType" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" use="required" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="VisualType">
    <xs:sequence minOccurs="0">
      <xs:choice maxOccurs="unbounded">
        <xs:element name="ImagerySection" type="ImagerySectionType" />
        <xs:element name="StateImagery" type="StateImageryType" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="AbsDimensionType">
    <xs:attribute name="x" use="optional" type="xs:decimal" />
    <xs:attribute name="y" use="optional" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="SizeType">
    <xs:sequence>
      <xs:element name="AbsDimension" type="AbsDimensionType" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="PositionType">
    <xs:sequence>
      <xs:element name="AbsDimension" type="AbsDimensionType" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="AnchorType">
    <xs:attribute name="point" use="required" type="AnchorPointType" />
    <xs:attribute name="relativePoint" use="optional" type="AnchorPointType" />
    <xs:attribute name="relativeTo" use="optional" type="xs:string" />
    <xs:attribute name="offset" use="optional" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="AreaType">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Size" type="SizeType" />
        <xs:element name="Position" type="PositionType" />
        <xs:element name="Anchor" type="AnchorType" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="EventsType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:any processContents="lax" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ScriptsType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="OnClick" type="ScriptBlockType" />
      <xs:element name="OnLoad" type="ScriptBlockType" />
      <xs:element name="OnUpdate" type="ScriptBlockType" />
      <xs:element name="OnTabPressed" type="ScriptBlockType" />
      <xs:element name="OnEnterPressed" type="ScriptBlockType" />
      <xs:element name="OnSpacePressed" type="ScriptBlockType" />
      <xs:element name="OnEscapePressed" type="ScriptBlockType" />
      <xs:element name="OnShow" type="ScriptBlockType" />
      <xs:element name="OnHide" type="ScriptBlockType" />
      <xs:element name="OnEnter" type="ScriptBlockType" />
      <xs:element name="OnLeave" type="ScriptBlockType" />
      <xs:element name="OnDrag" type="ScriptBlockType" />
      <xs:element name="OnDrop" type="ScriptBlockType" />
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="FrameType">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Property" type="PropertyType" />
        <xs:element name="Visual" type="VisualType" />
        <xs:element name="Area" type="AreaType" />
        <xs:element name="Events" type="EventsType" />
        <xs:element name="Scripts" type="ScriptsType" />
        <xs:element name="Frame" type="FrameType" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="type" type="xs:string" use="optional" />
    <xs:attribute name="renderer" type="FrameRendererType" use="optional" />
    <xs:attribute name="inherits" type="xs:string" use="optional" />
    <xs:attribute name="parent" type="xs:string" use="optional" />
    <xs:attribute name="setAllPoints" type="xs:boolean" use="optional" />
    <xs:attribute name="id" type="xs:int" use="optional" />
  </xs:complexType>

  <xs:element name="Frame" type="FrameType" />

  <xs:element name="UiLayout">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Script" minOccurs="0" maxOccurs="unbounded" type="ScriptFileType" />
        <xs:element name="Font" minOccurs="0" maxOccurs="unbounded" type="FontType" />
        <xs:element ref="Frame" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Kyoril/mmo-data/Interface/GameUI/AuraBar.xml
<?xml version="1.0" ?>
<UiLayout xmlns="http://www.w3schools.com/Ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com/Ui.xsd file:///F:/mmo/data/client/Interface/Ui.xsd">
	<Script file="AuraBar.lua" />

    <Frame name="AuraBar" parent="GameParent">
        <Area>
			<Anchor point="TOP" offset="8" />
			<Anchor point="RIGHT" offset="-416" />
            <Size>
                <AbsDimension x="1024" y="128" />
            </Size>
        </Area>

        <Frame name="AuraButton1" inherits="AuraBarButtonTemplate" id="1">
            <Area>
                <Anchor point="RIGHT" offset="0" />
                <Anchor point="TOP" offset="0" />
            </Area>
        </Frame>
        
        <Frame name="AuraButton2" inherits="AuraBarButtonTemplate" id="2">
            <Area>
                <Anchor point="RIGHT" relativeTo="AuraButton1" relativePoint="LEFT" offset="0" />
                <Anchor point="TOP" offset="0" />
            </Area>
        </Frame>
        
        <Frame name="AuraButton3" inherits="AuraBarButtonTemplate" id="3">
            <Area>
                <Anchor point="RIGHT" relativeTo="AuraButton2" relativePoint="LEFT" offset="0" />
                <Anchor point="TOP" offset="0" />
            </Area>
        </Frame>
        
        <Frame name="AuraButton4" inherits="AuraBarButtonTemplate" id="4">
            <Area>
                <Anchor point="RIGHT" relativeTo="AuraButton3" relativePoint="LEFT" offset="0" />
                <Anchor point="TOP" offset="0" />
            </Area>
        </Frame>
        
        <Frame name="AuraButton5" inherits="AuraBarButtonTemplate" id="5">
            <Area>
                <Anchor point="RIGHT" relativeTo="AuraButton4" relativePoint="LEFT" offset="0" />
                <Anchor point="TOP" offset="0" />
            </Area>
        </Frame>
        
        <Frame name="AuraButton6" inherits="AuraBarButtonTemplate" id="6">
            <Area>
                <Anchor point="RIGHT" relativeTo="AuraButton5" relativePoint="LEFT" offset="0" />
                <Anchor point="TOP" offset="0" />
            </Area>
        </Frame>
        
        <Frame name="AuraButton7" inherits="AuraBarButtonTemplate" id="7">
            <Area>
                <Anchor point="RIGHT" relativeTo="AuraButton6" relativePoint="LEFT" offset="0" />
                <Anchor point="TOP" offset="0" />
            </Area>
        </Frame>
        
        <Frame name="AuraButton8" inherits="AuraBarButtonTemplate" id="8">
            <Area>
                <Anchor point="RIGHT" relativeTo="AuraButton7" relativePoint="LEFT" offset="0" />
                <Anchor point="TOP" offset="0" />
            </Area>
        </Frame>

        <Scripts>
            <OnLoad>
                return function(this)
                    AuraBar_OnLoad(this);
                end
            </OnLoad>
        </Scripts>
    </Frame>
    
</UiLayout>

=== Kyoril/mmo-data/Interface/GameUI/GameMenuBar.xml
<?xml version="1.0" ?>
<UiLayout xmlns="http://www.w3schools.com/Ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com/Ui.xsd file:///F:/mmo/data/client/Interface/Ui.xsd">
	<Script file="GameMenuBar.lua" />
	
	<Frame name="GameMenuBarImageButton" type="Button" renderer="ButtonRenderer">
		<Property name="Icon" />

		<Visual>
			<ImagerySection name="Image">
				<ImageComponent>
					<Area>
						<Inset all="16" />
					</Area>
					<PropertyValue property="Icon" />
				</ImageComponent>
			</ImagerySection>
			<ImagerySection name="NormalFrame">
				<BorderComponent texture="Interface/BW_ButtonSmall_Up.htex" borderSize="30" />
			</ImagerySection>
			<ImagerySection name="HoveredFrame">
				<BorderComponent texture="Interface/BW_ButtonSmall_Over.htex" borderSize="30" />
			</ImagerySection>
			<ImagerySection name="PushedFrame">
				<BorderComponent texture="Interface/BW_ButtonSmall_Down.htex" borderSize="30" />
			</ImagerySection>
			<ImagerySection name="DisabledFrame">
				<BorderComponent texture="Interface/BW_ButtonSmall_Up.htex" borderSize="30" />
			</ImagerySection>
			<StateImagery name="Normal">
				<Layer>
					<Section section="NormalFrame" />
					<Section section="Image" />
				</Layer>
			</StateImagery>
			<StateImagery name="Hovered">
				<Layer>
					<Section section="HoveredFrame" />
					<Section section="Image" />
				</Layer>
			</StateImagery>
			<StateImagery name="Pushed">
				<Layer>
					<Section section="PushedFrame" />
					<Section section="Image" />
				</Layer>
			</StateImagery>
			<StateImagery name="Disabled">
				<Layer>
					<Section section="DisabledFrame" />
					<Section section="Image" />
				</Layer>
			</StateImagery>
		</Visual>
		<Area>
			<Size>
				<AbsDimension x="96" y="96" />
			</Size>
		</Area>
	</Frame>

	<Frame name="GameMenuBarButtonTemplate" inherits="GlueButton">
		<Area>
			<Size><AbsDimension x="400" y="96"/></Size>
			<Anchor point="LEFT" offset="16" />
		</Area>
	</Frame>

	<Frame name="GameMenuBar" renderer="DefaultRenderer" parent="GameParent">
		<Visual>
			<ImagerySection name="Background">
				<ImageComponent texture="Interface/GameUI/fg4_borders_stone_bg_01_result.htex" tiling="BOTH">
					<Area><Inset all="8" /></Area>
				</ImageComponent>
				<BorderComponent texture="Interface/GameUI/fg4_borders_stone_edges_result.htex" borderSize="45" />
			</ImagerySection>
			<StateImagery name="Enabled">
				<Layer>
					<!--<Section section="Background" />-->
				</Layer>
			</StateImagery>
		</Visual>

		<Frame name="PlayerExperienceBar" type="ProgressBar">
			<Property name="Progress" value="0.12783" />
			<Property name="Text" value="200 / 400" />
			<Property name="Font" value="DefaultSmall" />

			<Area>
				<Anchor point="LEFT" offset="8" />
				<Anchor point="RIGHT" offset="-8" />
				<Anchor point="BOTTOM" offset="0" />
				<Size><AbsDimension y="48" /></Size>
			</Area>

			<Visual>
				<ImagerySection name="Caption">
					<TextComponent color="FFFFFFFF" horzAlign="CENTER" vertAlign="CENTER" />
				</ImagerySection>
				<ImagerySection name="Background">
					<BorderComponent texture="Interface/fg4_borders_01_33.htex" borderSize="5" />
				</ImagerySection>
				<ImagerySection name="Border">
					<BorderComponent texture="Interface/GameUI/fg4_borders_insetBlack.htex" borderSize="24" />
				</ImagerySection>
				<ImagerySection name="Progress">
					<ImageComponent texture="Interface/fg4_gradientWhiteV1_result.htex" tiling="HORZ" tint="FF94008C">
						<Area><Inset all="8" /></Area>
					</ImageComponent>
				</ImagerySection>

				<StateImagery name="Enabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Disabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Progress">
					<Layer>
						<Section section="Progress" />
					</Layer>
				</StateImagery>
				<StateImagery name="Overlay">
					<Layer>
						<Section section="Border" />
						<Section section="Caption" />
					</Layer>
				</StateImagery>
			</Visual>
		</Frame>

		<Frame name="PlayerClassExperienceBar" type="ProgressBar">
			<Property name="Progress" value="0" />
			<Property name="Font" value="DefaultSmall" />
			<Property name="Visible" value="False" />

			<Area>
				<Anchor point="LEFT" offset="8" />
				<Anchor point="RIGHT" offset="-8" />
				<Anchor point="BOTTOM" offset="-48" />
				<Size><AbsDimension y="36" /></Size>
			</Area>

			<Visual>
				<ImagerySection name="Caption">
					<TextComponent color="FFFFFFFF" horzAlign="CENTER" vertAlign="CENTER" />
				</ImagerySection>
				<ImagerySection name="Background">
					<BorderComponent texture="Interface/fg4_borders_01_33.htex" borderSize="5" />
				</ImagerySection>
				<ImagerySection name="Border">
					<BorderComponent texture="Interface/GameUI/fg4_borders_insetBlackSmall.htex" borderSize="11" />
				</ImagerySection>
				<ImagerySection name="Progress">
					<ImageComponent texture="Interface/fg4_gradientWhiteV1_result.htex" tiling="HORZ" tint="FF9E5E22">
						<Area><Inset all="6" /></Area>
					</ImageComponent>
				</ImagerySection>

				<StateImagery name="Enabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Disabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Progress">
					<Layer>
						<Section section="Progress" />
					</Layer>
				</StateImagery>
				<StateImagery name="Overlay">
					<Layer>
						<Section section="Border" />
						<Section section="Caption" />
					</Layer>
				</StateImagery>
			</Visual>
		</Frame>

<!--
		<Frame name="LeftSideDecoration" renderer="DefaultRenderer">
			<Area>
				<Anchor point="LEFT" relativePoint="LEFT" offset="64" />
				<Anchor point="BOTTOM" relativePoint="BOTTOM" offset="48" />
				<Size><AbsDimension x="-256" y="256" /></Size>
			</Area>

			<Visual>
				<ImagerySection name="Background">
					<ImageComponent texture="Interface/GameUI/fg4_icons_emblemLion_result.htex" tiling="NONE" />
				</ImagerySection>

				<StateImagery name="Enabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
			</Visual>
		</Frame>

		<Frame name="RightSideDecoration" renderer="DefaultRenderer">
			<Area>
				<Anchor point="LEFT" relativePoint="RIGHT" offset="-64" />
				<Anchor point="BOTTOM" relativePoint="BOTTOM" offset="48" />
				<Size><AbsDimension x="256" y="256" /></Size>
			</Area>

			<Visual>
				<ImagerySection name="Background">
					<ImageComponent texture="Interface/GameUI/fg4_icons_emblemLion_result.htex" tiling="NONE" />
				</ImagerySection>

				<StateImagery name="Enabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
			</Visual>
		</Frame>
-->
		<Area>
			<Size><AbsDimension x="1580" y="224" /></Size>
			<Anchor point="BOTTOM" offset="0" />
			<Anchor point="H_CENTER" offset="0" />
		</Area>

		<Scripts>
			<OnLoad>
				return function(this)
					GameMenuBar_OnLoad(this);
				end
			</OnLoad>
		</Scripts>
	</Frame>
	
		<Frame name="MenuBarButtons" parent="GameParent">
			<Area>
				<Anchor point="RIGHT" />
				<Anchor point="BOTTOM" />
				<Size><AbsDimension x="640" y="96" /></Size>
			</Area>
			
			<Visual>
				<ImagerySection name="Background">
					<BorderComponent texture="Interface/GameUI/fg4_borders_insetBlack.htex" borderSize="30">
						<Area><Inset bottom="8" left="0" top="8" right="8" /></Area>
					</BorderComponent>
				</ImagerySection>

				<StateImagery name="Enabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
			</Visual>
		</Frame>

</UiLayout>

=== Kyoril/mmo-data/Interface/GameUI/LootRollFrame.xml
<?xml version="1.0" ?>
<UiLayout xmlns="http://www.w3schools.com/Ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com/Ui.xsd file:///F:/mmo/data/client/Interface/Ui.xsd">
	<Script file="LootRollFrame.lua" />

	<!-- Compact text button using small border textures (borderSize=22, safe at 48px height) -->
	<Frame name="LootRollChoiceButtonTemplate" type="Button" renderer="ButtonRenderer">
		<Property name="Font" value="SmallLabelFont" />

		<Visual>
			<ImagerySection name="NormalFrame">
				<BorderComponent texture="Interface/GameUI/fg4_buttonSmall1_Up_result.htex" borderSize="22" />
			</ImagerySection>
			<ImagerySection name="HoveredFrame">
				<BorderComponent texture="Interface/GameUI/fg4_buttonSmall1_Over_result.htex" borderSize="22" />
			</ImagerySection>
			<ImagerySection name="PushedFrame">
				<BorderComponent texture="Interface/GameUI/fg4_buttonSmall1_Down_result.htex" borderSize="22" />
			</ImagerySection>
			<ImagerySection name="DisabledFrame">
				<BorderComponent texture="Interface/GameUI/fg4_buttonSmall2_Disabled_result.htex" borderSize="22" />
			</ImagerySection>
			<ImagerySection name="Caption">
				<TextComponent color="FFFFD100" horzAlign="CENTER" vertAlign="CENTER" />
			</ImagerySection>
			<ImagerySection name="HoveredCaption">
				<TextComponent color="FFFFFFFF" horzAlign="CENTER" vertAlign="CENTER" />
			</ImagerySection>
			<StateImagery name="Normal">
				<Layer>
					<Section section="NormalFrame" />
					<Section section="Caption" />
				</Layer>
			</StateImagery>
			<StateImagery name="Hovered">
				<Layer>
					<Section section="HoveredFrame" />
					<Section section="HoveredCaption" />
				</Layer>
			</StateImagery>
			<StateImagery name="Pushed">
				<Layer>
					<Section section="PushedFrame" />
					<Section section="Caption" color="FFAAAAAA" />
				</Layer>
			</StateImagery>
			<StateImagery name="Disabled">
				<Layer>
					<Section section="DisabledFrame" />
					<Section section="Caption" color="AE888888" />
				</Layer>
			</StateImagery>
		</Visual>

		<Area>
			<Size><AbsDimension x="88" y="48" /></Size>
		</Area>
	</Frame>

	<!-- Roll item row: [Icon] [ItemName / Timer] [Need] [Greed] [Pass] -->
	<!-- Children order: 0=Icon, 1=Name, 2=Timer, 3=NeedButton, 4=GreedButton, 5=PassButton -->
	<Frame name="LootRollItemTemplate" renderer="DefaultRenderer">
		<Area>
			<Size><AbsDimension x="480" y="68" /></Size>
		</Area>

		<Visual>
			<ImagerySection name="Background">
				<BorderComponent texture="Interface/GameUI/fg4_borders_01_19.htex" borderSize="25" />
			</ImagerySection>
			<StateImagery name="Enabled">
				<Layer>
					<Section section="Background" />
				</Layer>
			</StateImagery>
		</Visual>

		<!-- Child 0: Item icon -->
		<Frame name="Icon" renderer="DefaultRenderer">
			<Property name="Icon" value="" />

			<Area>
				<Position><AbsDimension x="10" y="10" /></Position>
				<Size><AbsDimension x="48" y="48" /></Size>
			</Area>

			<Visual>
				<ImagerySection name="Image">
					<ImageComponent tiling="NONE">
						<PropertyValue property="Icon" />
					</ImageComponent>
				</ImagerySection>
				<StateImagery name="Enabled">
					<Layer>
						<Section section="Image" color="FFFFFFFF" />
					</Layer>
				</StateImagery>
				<StateImagery name="Disabled">
					<Layer>
						<Section section="Image" color="AE888888" />
					</Layer>
				</StateImagery>
			</Visual>
		</Frame>

		<!-- Child 1: Item name -->
		<Frame name="Name" renderer="DefaultRenderer">
			<Property name="Font" value="SmallLabelFont" />

			<Area>
				<Position><AbsDimension x="66" y="8" /></Position>
				<Size><AbsDimension x="144" y="28" /></Size>
			</Area>

			<Visual>
				<ImagerySection name="Text">
					<TextComponent color="FFFFFFFF" horzAlign="LEFT" vertAlign="CENTER" />
				</ImagerySection>
				<StateImagery name="Enabled">
					<Layer>
						<Section section="Text" />
					</Layer>
				</StateImagery>
				<StateImagery name="Disabled">
					<Layer>
						<Section section="Text" />
					</Layer>
				</StateImagery>
			</Visual>
		</Frame>

		<!-- Child 2: Timer text -->
		<Frame name="Timer" renderer="DefaultRenderer">
			<Property name="Font" value="AuraTimeFont" />

			<Area>
				<Position><AbsDimension x="66" y="38" /></Position>
				<Size><AbsDimension x="100" y="22" /></Size>
			</Area>

			<Visual>
				<ImagerySection name="Text">
					<TextComponent color="FFAAAAAA" horzAlign="LEFT" vertAlign="CENTER" />
				</ImagerySection>
				<StateImagery name="Enabled">
					<Layer>
						<Section section="Text" />
					</Layer>
				</StateImagery>
				<StateImagery name="Disabled">
					<Layer>
						<Section section="Text" />
					</Layer>
				</StateImagery>
			</Visual>
		</Frame>

		<!-- Child 3: Need button -->
		<Frame name="NeedButton" type="Button" inherits="LootRollChoiceButtonTemplate">
			<Property name="Text" value="Need" />
			<Area>
				<Position><AbsDimension x="216" y="10" /></Position>
			</Area>
		</Frame>

		<!-- Child 4: Greed button -->
		<Frame name="GreedButton" type="Button" inherits="LootRollChoiceButtonTemplate">
			<Property name="Text" value="Greed" />
			<Area>
				<Position><AbsDimension x="308" y="10" /></Position>
			</Area>
		</Frame>

		<!-- Child 5: Pass button -->
		<Frame name="PassButton" type="Button" inherits="LootRollChoiceButtonTemplate">
			<Property name="Text" value="Pass" />
			<Area>
				<Position><AbsDimension x="400" y="10" /></Position>
			</Area>
		</Frame>
	</Frame>

	<!-- Invisible container: no background, positioned top-center -->
	<Frame name="LootRollFrame" parent="GameParent" renderer="DefaultRenderer">
		<Property name="Visible" value="false" />

		<Area>
			<Size><AbsDimension x="500" y="296" /></Size>
			<Anchor point="H_CENTER" />
			<Anchor point="TOP" offset="120" />
		</Area>

		<Scripts>
			<OnLoad>
				return function(self)
					LootRollFrame_OnLoad(self);
				end
			</OnLoad>
			<OnUpdate>
				return function(self, elapsed)
					LootRollFrame_OnUpdate(self, elapsed);
				end
			</OnUpdate>
		</Scripts>

		<Frame name="LootRollItem1" inherits="LootRollItemTemplate">
			<Area>
				<Anchor point="TOP" offset="4" />
				<Anchor point="H_CENTER" />
			</Area>
		</Frame>

		<Frame name="LootRollItem2" inherits="LootRollItemTemplate">
			<Area>
				<Anchor point="TOP" relativePoint="BOTTOM" relativeTo="LootRollItem1" offset="4" />
				<Anchor point="H_CENTER" />
			</Area>
		</Frame>

		<Frame name="LootRollItem3" inherits="LootRollItemTemplate">
			<Area>
				<Anchor point="TOP" relativePoint="BOTTOM" relativeTo="LootRollItem2" offset="4" />
				<Anchor point="H_CENTER" />
			</Area>
		</Frame>

		<Frame name="LootRollItem4" inherits="LootRollItemTemplate">
			<Area>
				<Anchor point="TOP" relativePoint="BOTTOM" relativeTo="LootRollItem3" offset="4" />
				<Anchor point="H_CENTER" />
			</Area>
		</Frame>
	</Frame>
</UiLayout>

=== Kyoril/mmo-data/Interface/GameUI/ZoneText.xml
<?xml version="1.0" ?>
<UiLayout xmlns="http://www.w3schools.com/Ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com/Ui.xsd file:///F:/mmo/data/client/Interface/Ui.xsd">
	<Script file="ZoneText.lua" />

    <Font name="ZoneTextFont" file="Fonts/FRIZQT__.TTF" size="64" outline="3" />
    <Font name="ZoneTextFontSmall" file="Fonts/FRIZQT__.TTF" size="48" outline="3" />
	
    <Frame name="ZoneText" inherits="TextSmall" parent="GameParent">
        <Property name="Font" value="ZoneTextFont" />
		<Property name="HorzAlign" value="CENTER" />
		<Property name="TextColor" value="FF19FF19" />

		<Area>
			<Size>
				<AbsDimension y="96" />
				<Anchor point="LEFT" />
                <Anchor point="RIGHT" />
				<Anchor point="V_CENTER" offset="-256" />
			</Size>
		</Area>

		<Scripts>
			<OnLoad>
				return function(this)
					ZoneText_OnLoad(ZoneText);
				end
			</OnLoad>
            <OnUpdate>
                return function(this, elapsed)
                    ZoneText_OnUpdate(ZoneText, elapsed);
                end
            </OnUpdate>
		</Scripts>
    </Frame>
    <Frame name="ZoneSubText" inherits="TextSmall" parent="GameParent">
        <Property name="Font" value="ZoneTextFontSmall" />
		<Property name="HorzAlign" value="CENTER" />
		<Property name="TextColor" value="FF19FF19" />

		<Area>
			<Size>
				<AbsDimension y="64" />
				<Anchor point="LEFT" />
                <Anchor point="RIGHT" />
				<Anchor point="TOP" relativePoint="BOTTOM" relativeTo="ZoneText" />
			</Size>
		</Area>

		<Scripts>
			<OnLoad>
				return function(this)
					ZoneText_OnLoad(ZoneSubText);
				end
			</OnLoad>
            <OnUpdate>
                return function(this, elapsed)
                    ZoneText_OnUpdate(ZoneSubText, elapsed);
                end
            </OnUpdate>
		</Scripts>
    </Frame>
</UiLayout>
