=== Kyoril/mmo-data/Interface/GlueUI/Ui.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://mmo-dev.net/ui"
    elementFormDefault="qualified"
    xmlns="http://mmo-dev.net/ui"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="FrameRendererType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="DefaultRenderer" />
      <xs:enumeration value="ButtonRenderer" />
      <xs:enumeration value="CheckboxRenderer" />
      <xs:enumeration value="TextFieldRenderer" />
      <xs:enumeration value="ModelRenderer" />
      <xs:enumeration value="WorldRenderer" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="AnchorPointType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="LEFT" />
      <xs:enumeration value="TOP" />
      <xs:enumeration value="RIGHT" />
      <xs:enumeration value="BOTTOM" />
      <xs:enumeration value="H_CENTER" />
      <xs:enumeration value="V_CENTER" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TilingType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="NONE" />
      <xs:enumeration value="HORZ" />
      <xs:enumeration value="VERT" />
      <xs:enumeration value="BOTH" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="HorzAlignType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="LEFT" />
      <xs:enumeration value="CENTER" />
      <xs:enumeration value="RIGHT" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="VertAlignType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="TOP" />
      <xs:enumeration value="CENTER" />
      <xs:enumeration value="BOTTOM" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="ScriptFileType">
    <xs:attribute name="file" use="required" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="ScriptBlockType">
    <xs:simpleContent>
      <xs:extension base="xs:string" />
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="FontType">
    <xs:attribute name="name" use="required" type="xs:string" />
    <xs:attribute name="file" use="required" type="xs:string" />
    <xs:attribute name="size" use="required" type="xs:decimal" />
    <xs:attribute name="outline" use="optional" type="xs:decimal" />
    <xs:attribute name="shadowX" use="optional" type="xs:decimal" />
    <xs:attribute name="shadowY" use="optional" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="PropertyType">
    <xs:attribute name="name" use="required" type="xs:string" />
    <xs:attribute name="value" use="optional" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="PropertyValueType">
    <xs:attribute name="property" use="required" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="InsetType">
    <xs:attribute name="all" use="optional" type="xs:decimal" />
    <xs:attribute name="left" use="optional" type="xs:decimal" />
    <xs:attribute name="top" use="optional" type="xs:decimal" />
    <xs:attribute name="right" use="optional" type="xs:decimal" />
    <xs:attribute name="bottom" use="optional" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="AreaComponentType">
    <xs:sequence minOccurs="0" maxOccurs="1">
      <xs:element name="Inset" type="InsetType" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="BorderComponentType">
    <xs:sequence minOccurs="0" maxOccurs="1">
      <xs:element name="Area" type="AreaComponentType" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="texture" use="required" type="xs:string" />
    <xs:attribute name="borderSize" use="optional" type="xs:decimal" />
    <xs:attribute name="topSize" use="optional" type="xs:decimal" />
    <xs:attribute name="leftSize" use="optional" type="xs:decimal" />
    <xs:attribute name="rightSize" use="optional" type="xs:decimal" />
    <xs:attribute name="bottomSize" use="optional" type="xs:decimal" />
    <xs:attribute name="tint" use="optional" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="ImageComponentType">
    <xs:sequence minOccurs="0" maxOccurs="2">
      <xs:choice>
        <xs:element name="Area" type="AreaComponentType" minOccurs="0" maxOccurs="1" />
        <xs:element name="PropertyValue" type="PropertyValueType" minOccurs="0" maxOccurs="1" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="texture" use="optional" type="xs:string" />
    <xs:attribute name="tint" use="optional" type="xs:string" />
    <xs:attribute name="tiling" use="optional" type="TilingType" />
  </xs:complexType>

  <xs:complexType name="TextComponentType">
    <xs:sequence minOccurs="0" maxOccurs="1">
      <xs:element name="Area" type="AreaComponentType" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="color" use="optional" type="xs:string" />
    <xs:attribute name="horzAlign" use="optional" type="HorzAlignType" />
    <xs:attribute name="vertAlign" use="optional" type="VertAlignType" />
    <xs:attribute name="wrap" use="optional" type="xs:boolean" />
  </xs:complexType>

  <xs:complexType name="ImagerySectionType">
    <xs:sequence>
      <xs:choice maxOccurs="unbounded">
        <xs:element name="BorderComponent" type="BorderComponentType" />
        <xs:element name="ImageComponent" type="ImageComponentType" />
        <xs:element name="TextComponent" type="TextComponentType" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="name" use="required" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="SectionType">
    <xs:attribute name="section" use="required" type="xs:string" />
    <xs:attribute name="color" use="optional" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="LayerType">
    <xs:sequence>
      <xs:element name="Section" maxOccurs="unbounded" minOccurs="1" type="SectionType" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="StateImageryType">
    <xs:sequence>
      <xs:element name="Layer" type="LayerType" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" use="required" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="VisualType">
    <xs:sequence minOccurs="0">
      <xs:choice maxOccurs="unbounded">
        <xs:element name="ImagerySection" type="ImagerySectionType" />
        <xs:element name="StateImagery" type="StateImageryType" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="AbsDimensionType">
    <xs:attribute name="x" use="optional" type="xs:decimal" />
    <xs:attribute name="y" use="optional" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="SizeType">
    <xs:sequence>
      <xs:element name="AbsDimension" type="AbsDimensionType" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="PositionType">
    <xs:sequence>
      <xs:element name="AbsDimension" type="AbsDimensionType" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="AnchorType">
    <xs:attribute name="point" use="required" type="AnchorPointType" />
    <xs:attribute name="relativePoint" use="optional" type="AnchorPointType" />
    <xs:attribute name="relativeTo" use="optional" type="xs:string" />
    <xs:attribute name="offset" use="optional" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="AreaType">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Size" type="SizeType" />
        <xs:element name="Position" type="PositionType" />
        <xs:element name="Anchor" type="AnchorType" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="EventsType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:any processContents="lax" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ScriptsType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="OnClick" type="ScriptBlockType" />
      <xs:element name="OnLoad" type="ScriptBlockType" />
      <xs:element name="OnUpdate" type="ScriptBlockType" />
      <xs:element name="OnTabPressed" type="ScriptBlockType" />
      <xs:element name="OnEnterPressed" type="ScriptBlockType" />
      <xs:element name="OnSpacePressed" type="ScriptBlockType" />
      <xs:element name="OnEscapePressed" type="ScriptBlockType" />
      <xs:element name="OnShow" type="ScriptBlockType" />
      <xs:element name="OnHide" type="ScriptBlockType" />
      <xs:element name="OnEnter" type="ScriptBlockType" />
      <xs:element name="OnLeave" type="ScriptBlockType" />
      <xs:element name="OnDrag" type="ScriptBlockType" />
      <xs:element name="OnDrop" type="ScriptBlockType" />
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="FrameType">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Property" type="PropertyType" />
        <xs:element name="Visual" type="VisualType" />
        <xs:element name="Area" type="AreaType" />
        <xs:element name="Events" type="EventsType" />
        <xs:element name="Scripts" type="ScriptsType" />
        <xs:element name="Frame" type="FrameType" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="type" type="xs:string" use="optional" />
    <xs:attribute name="renderer" type="FrameRendererType" use="optional" />
    <xs:attribute name="inherits" type="xs:string" use="optional" />
    <xs:attribute name="parent" type="xs:string" use="optional" />
    <xs:attribute name="setAllPoints" type="xs:boolean" use="optional" />
    <xs:attribute name="id" type="xs:int" use="optional" />
  </xs:complexType>

  <xs:element name="Frame" type="FrameType" />

  <xs:element name="UiLayout">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Script" minOccurs="0" maxOccurs="unbounded" type="ScriptFileType" />
        <xs:element name="Font" minOccurs="0" maxOccurs="unbounded" type="FontType" />
        <xs:element ref="Frame" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Kyoril/mmo-data/Interface/GameUI/GameTooltip.xml
<?xml version="1.0" ?>
<UiLayout xmlns="http://www.w3schools.com/Ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com/Ui.xsd file:///F:/mmo/data/client/Interface/Ui.xsd">
	<Script file="GameTooltip.lua" />
	
	<Font name="TooltipTitleFont" file="Fonts/FRIZQT__.TTF" size="28" outline="0" shadowX="1.0" shadowY="1.0" />
	<Font name="TooltipFont" file="Fonts/FRIZQT__.TTF" size="24" outline="0" shadowX="1.0" shadowY="1.0" />

    <Frame name="GameTooltipLineTemplate" renderer="DefaultRenderer">
		<Property name="Font" value="TooltipFont" />

        <Visual>
			<ImagerySection name="Text">
				<TextComponent color="FFFFFFFF" horzAlign="LEFT" vertAlign="TOP" />
            </ImagerySection>

			<StateImagery name="Enabled">
				<Layer>
					<Section section="Text" />
				</Layer>
			</StateImagery>
			<StateImagery name="Disabled">
				<Layer>
					<Section section="Text" />
				</Layer>
			</StateImagery>
        </Visual>
        <Area>
            <Size><AbsDimension x="512" y="32" /></Size>
        </Area>
    </Frame>

	<Frame name="GameTooltipIconLineTemplate" renderer="DefaultRenderer">
		<Area>
			<Size><AbsDimension x="512" y="32" /></Size>
		</Area>

		<Frame name="GameTooltipLineIcon" inherits="IconTemplate">
			<Area>
				<Anchor point="LEFT" />
				<Anchor point="TOP" />
				<Size><AbsDimension x="32" y="32" /></Size>
			</Area>
		</Frame>

		<Frame name="GameTooltipLineIconText" inherits="GameTooltipLineTemplate">
			<Area>
				<Anchor point="LEFT" relativeTo="GameTooltipLineIcon" relativePoint="RIGHT" offset="8" />
				<Anchor point="RIGHT" />
				<Anchor point="TOP" />
				<Size><AbsDimension x="0" y="32" /></Size>
			</Area>
		</Frame>
	</Frame>

    <Frame name="GameTooltipLineRightTemplate" renderer="DefaultRenderer">
		<Property name="Font" value="TooltipFont" />

        <Visual>
			<ImagerySection name="Text">
				<TextComponent color="FFFFFFFF" horzAlign="RIGHT" vertAlign="TOP" />
            </ImagerySection>

			<StateImagery name="Enabled">
				<Layer>
					<Section section="Text" />
				</Layer>
			</StateImagery>
			<StateImagery name="Disabled">
				<Layer>
					<Section section="Text" />
				</Layer>
			</StateImagery>
        </Visual>
        <Area>
            <Size><AbsDimension x="512" y="32" /></Size>
        </Area>
    </Frame>
    
    <Frame name="GameTooltip" renderer="DefaultRenderer" parent="GameParent">
		<Property name="Visible" value="False" />
		
		<Visual>
			<ImagerySection name="Background">
				<ImageComponent texture="Interface/GlueUI/TransparentBorder.htex" tiling="NONE">
					<Area><Inset all="8" /></Area>
                </ImageComponent>
				<BorderComponent texture="Interface/GameUI/fg4_borders_stone_edges_result.htex" borderSize="32" />
			</ImagerySection>
			<StateImagery name="Enabled">
				<Layer>
					<Section section="Background" />
				</Layer>
			</StateImagery>
		</Visual>

        <Frame name="GameTooltipLines">
            <Area>
                <Anchor point="TOP" relativePoint="TOP" offset="16" />
                <Anchor point="LEFT" offset="8" />
                <Anchor point="RIGHT" offset="-8" />
                <Anchor point="BOTTOM" offset="-8" />
            </Area>
        </Frame>

		<Frame name="TooltipMoneyText" inherits="TextSmall">
			<Property name="Text" value="SELL_PRICE" />
			<Property name="Font" value="SmallLabelFont" />
			
            <Area>
                <Anchor point="LEFT" offset="16" />
                <Anchor point="RIGHT" offset="-16" />
                <Anchor point="BOTTOM" offset="-16" />
            </Area>
		</Frame>

		<Frame name="TooltipMoneyFrame" inherits="MoneyFrameTemplate">
			<Property name="Visible" value="False" />
			
			<Area>
				<Anchor point="BOTTOM" offset="-16" />
				<Anchor point="LEFT" offset="16" />
				<Anchor point="RIGHT" offset="-16" />
			</Area>
		</Frame>

		<Area>
			<Size><AbsDimension x="540" y="96" /></Size>
			<Anchor point="RIGHT" offset="-64" />
			<Anchor point="BOTTOM" offset="-64" />
		</Area>

		<Scripts>
			<OnLoad>
				return function(self)
					GameTooltip_OnLoad(self);
				end
			</OnLoad>
			<OnUpdate>
				return function(self, deltaTime)
					GameTooltip_OnUpdate(self, deltaTime);
				end
			</OnUpdate>
		</Scripts>
	</Frame>
</UiLayout>

=== Kyoril/mmo-data/Interface/GameUI/PartyFrame.xml
<?xml version="1.0" ?>
<UiLayout xmlns="http://www.w3schools.com/Ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="file:\\F:\mmo\data\client\Interface\Ui.xsd">
	<Script file="PartyFrame.lua" />

    <Frame name="PartyMemberFrameTemplate">
        <Area>
            <Size><AbsDimension x="320" y="128" /></Size>
        </Area>

        <Frame name="PartyName" inherits="TextSmall">
            <Property name="Text" value="UNKNOWN" />
            <Property name="Font" value="SmallLabelFont" />

            <Area>
                <Anchor point="LEFT" />
                <Anchor point="RIGHT" />
                <Anchor point="TOP" />
                <Size><AbsDimension y="42" /></Size>
            </Area>
        </Frame>

        <Frame name="PartyHealthBar" type="ProgressBar">
            <Property name="Progress" value="0.12783" />
			<Property name="Font" value="DefaultSmall" />

            <Area>
                <Anchor point="LEFT" />
                <Anchor point="RIGHT" />
                <Anchor point="TOP" relativeTo="PartyName" relativePoint="BOTTOM" />
                <Size><AbsDimension y="32" /></Size>
            </Area>
            
			<Visual>
				<ImagerySection name="Caption">
					<TextComponent color="FFFFFFFF" horzAlign="CENTER" vertAlign="CENTER" />
				</ImagerySection>
				<ImagerySection name="Background">
					<BorderComponent texture="Interface/fg4_borders_01_33.htex" borderSize="5" />
				</ImagerySection>
				<ImagerySection name="Border">
					<BorderComponent texture="Interface/GameUI/fg4_borders_insetBlackSmall.htex" borderSize="11" />
				</ImagerySection>
				<ImagerySection name="Progress">
					<ImageComponent texture="Interface/fg4_gradientWhiteV1_result.htex" tiling="HORZ" tint="FF00FF00">
						<Area><Inset all="8" /></Area>
					</ImageComponent>
				</ImagerySection>

				<StateImagery name="Enabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Disabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Progress">
					<Layer>
						<Section section="Progress" />
					</Layer>
				</StateImagery>
				<StateImagery name="Overlay">
					<Layer>
						<Section section="Border" />
						<Section section="Caption" />
					</Layer>
				</StateImagery>
			</Visual>
        </Frame>

		<Frame name="PartyManaBar" type="ProgressBar">
			<Property name="Progress" value="0.12783" />
			<Property name="Font" value="DefaultSmall" />

			<Area>
				<Anchor point="LEFT" />
				<Anchor point="RIGHT" />
				<Anchor point="TOP" relativePoint="BOTTOM" relativeTo="PartyHealthBar" />
				<Size><AbsDimension y="32" /></Size>
			</Area>

			<Visual>
				<ImagerySection name="Caption">
					<TextComponent color="FFFFFFFF" horzAlign="CENTER" vertAlign="CENTER" />
				</ImagerySection>
				<ImagerySection name="Background">
					<BorderComponent texture="Interface/fg4_borders_01_33.htex" borderSize="5" />
				</ImagerySection>
				<ImagerySection name="Border">
					<BorderComponent texture="Interface/GameUI/fg4_borders_insetBlackSmall.htex" borderSize="11" />
				</ImagerySection>
				<ImagerySection name="Progress">
					<ImageComponent texture="Interface/fg4_gradientWhiteV1_result.htex" tiling="HORZ">
						<Area><Inset all="8" /></Area>
					</ImageComponent>
				</ImagerySection>

				<StateImagery name="Enabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Disabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Progress">
					<Layer>
						<Section section="Progress" />
					</Layer>
				</StateImagery>
				<StateImagery name="Overlay">
					<Layer>
						<Section section="Border" />
						<Section section="Caption" />
					</Layer>
				</StateImagery>
			</Visual>
		</Frame>
    
        <Frame name="PartyLeaderIcon" inherits="IconTemplate">
            <Property name="Visible" value="false" />
            <Property name="Icon" value="Interface/Icons/fg4_iconsGold_crown_result.htex" />

            <Area>
                <Anchor point="TOP" />
                <Anchor point="LEFT" />
            </Area>
        </Frame>

        <Frame name="ClickFrame" type="Button" setAllPoints="true" />
    </Frame>

    <Frame name="PartyFrame" parent="GameParent" renderer="DefaultRenderer">
        <Property name="Visible" value="false" />

        <Area>
            <Anchor point="LEFT" offset="32" />
            <Anchor point="TOP" relativePoint="BOTTOM" relativeTo="PlayerFrame" offset="32" />
            <Size><AbsDimension x="320" y="532" /></Size>
        </Area>

		<Visual>
			<ImagerySection name="Background">
                <BorderComponent texture="Interface/GameUI/fg4_gradientBlackCircle2.htex" borderSize="31" tint="81FFFFFF" />
            </ImagerySection>
            <StateImagery name="Enabled">
                <Layer>
                    <Section section="Background" />
                </Layer>
            </StateImagery>
            <StateImagery name="Disabled">
                <Layer>
                    <Section section="Background" />
                </Layer>
            </StateImagery>
		</Visual>

        <Frame name="PartyMember1" inherits="PartyMemberFrameTemplate" id="1">
            <Property name="Visible" value="false" />

            <Area>
                <Anchor point="LEFT" offset="10" />
                <Anchor point="RIGHT" offset="-10" />
                <Anchor point="TOP" offset="10" />
            </Area>

            <Scripts>
                <OnLoad>
                    return function(self)
                        PartyMemberFrame_OnLoad(self);
                    end
                </OnLoad>
            </Scripts>
        </Frame>

        <Frame name="PartyMember2" inherits="PartyMemberFrameTemplate" id="2">
            <Property name="Visible" value="false" />

            <Area>
                <Anchor point="LEFT" offset="10" />
                <Anchor point="RIGHT" offset="-10" />
                <Anchor point="TOP" relativePoint="BOTTOM" relativeTo="PartyMember1" />
            </Area>

            <Scripts>
                <OnLoad>
                    return function(self)
                        PartyMemberFrame_OnLoad(self);
                    end
                </OnLoad>
            </Scripts>
        </Frame>

        <Frame name="PartyMember3" inherits="PartyMemberFrameTemplate" id="3">
            <Property name="Visible" value="false" />

            <Area>
                <Anchor point="LEFT" offset="10" />
                <Anchor point="RIGHT" offset="-10" />
                <Anchor point="TOP" relativePoint="BOTTOM" relativeTo="PartyMember2" />
            </Area>

            <Scripts>
                <OnLoad>
                    return function(self)
                        PartyMemberFrame_OnLoad(self);
                    end
                </OnLoad>
            </Scripts>
        </Frame>

        <Frame name="PartyMember4" inherits="PartyMemberFrameTemplate" id="4">
            <Property name="Visible" value="false" />
            
            <Area>
                <Anchor point="LEFT" offset="10" />
                <Anchor point="RIGHT" offset="-10" />
                <Anchor point="TOP" relativePoint="BOTTOM" relativeTo="PartyMember3" />
            </Area>

            <Scripts>
                <OnLoad>
                    return function(self)
                        PartyMemberFrame_OnLoad(self);
                    end
                </OnLoad>
            </Scripts>
        </Frame>

        <Scripts>
            <OnLoad>
                return function(self)
                    PartyFrame_OnLoad(self);
                end
            </OnLoad>
        </Scripts>
    </Frame>
</UiLayout>
