=== Kyoril/mmo-data/Interface/GlueUI/Ui.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://mmo-dev.net/ui"
    elementFormDefault="qualified"
    xmlns="http://mmo-dev.net/ui"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="FrameRendererType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="DefaultRenderer" />
      <xs:enumeration value="ButtonRenderer" />
      <xs:enumeration value="CheckboxRenderer" />
      <xs:enumeration value="TextFieldRenderer" />
      <xs:enumeration value="ModelRenderer" />
      <xs:enumeration value="WorldRenderer" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="AnchorPointType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="LEFT" />
      <xs:enumeration value="TOP" />
      <xs:enumeration value="RIGHT" />
      <xs:enumeration value="BOTTOM" />
      <xs:enumeration value="H_CENTER" />
      <xs:enumeration value="V_CENTER" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TilingType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="NONE" />
      <xs:enumeration value="HORZ" />
      <xs:enumeration value="VERT" />
      <xs:enumeration value="BOTH" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="HorzAlignType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="LEFT" />
      <xs:enumeration value="CENTER" />
      <xs:enumeration value="RIGHT" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="VertAlignType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="TOP" />
      <xs:enumeration value="CENTER" />
      <xs:enumeration value="BOTTOM" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="ScriptFileType">
    <xs:attribute name="file" use="required" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="ScriptBlockType">
    <xs:simpleContent>
      <xs:extension base="xs:string" />
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="FontType">
    <xs:attribute name="name" use="required" type="xs:string" />
    <xs:attribute name="file" use="required" type="xs:string" />
    <xs:attribute name="size" use="required" type="xs:decimal" />
    <xs:attribute name="outline" use="optional" type="xs:decimal" />
    <xs:attribute name="shadowX" use="optional" type="xs:decimal" />
    <xs:attribute name="shadowY" use="optional" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="PropertyType">
    <xs:attribute name="name" use="required" type="xs:string" />
    <xs:attribute name="value" use="optional" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="PropertyValueType">
    <xs:attribute name="property" use="required" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="InsetType">
    <xs:attribute name="all" use="optional" type="xs:decimal" />
    <xs:attribute name="left" use="optional" type="xs:decimal" />
    <xs:attribute name="top" use="optional" type="xs:decimal" />
    <xs:attribute name="right" use="optional" type="xs:decimal" />
    <xs:attribute name="bottom" use="optional" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="AreaComponentType">
    <xs:sequence minOccurs="0" maxOccurs="1">
      <xs:element name="Inset" type="InsetType" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="BorderComponentType">
    <xs:sequence minOccurs="0" maxOccurs="1">
      <xs:element name="Area" type="AreaComponentType" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="texture" use="required" type="xs:string" />
    <xs:attribute name="borderSize" use="optional" type="xs:decimal" />
    <xs:attribute name="topSize" use="optional" type="xs:decimal" />
    <xs:attribute name="leftSize" use="optional" type="xs:decimal" />
    <xs:attribute name="rightSize" use="optional" type="xs:decimal" />
    <xs:attribute name="bottomSize" use="optional" type="xs:decimal" />
    <xs:attribute name="tint" use="optional" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="ImageComponentType">
    <xs:sequence minOccurs="0" maxOccurs="2">
      <xs:choice>
        <xs:element name="Area" type="AreaComponentType" minOccurs="0" maxOccurs="1" />
        <xs:element name="PropertyValue" type="PropertyValueType" minOccurs="0" maxOccurs="1" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="texture" use="optional" type="xs:string" />
    <xs:attribute name="tint" use="optional" type="xs:string" />
    <xs:attribute name="tiling" use="optional" type="TilingType" />
  </xs:complexType>

  <xs:complexType name="TextComponentType">
    <xs:sequence minOccurs="0" maxOccurs="1">
      <xs:element name="Area" type="AreaComponentType" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="color" use="optional" type="xs:string" />
    <xs:attribute name="horzAlign" use="optional" type="HorzAlignType" />
    <xs:attribute name="vertAlign" use="optional" type="VertAlignType" />
    <xs:attribute name="wrap" use="optional" type="xs:boolean" />
  </xs:complexType>

  <xs:complexType name="ImagerySectionType">
    <xs:sequence>
      <xs:choice maxOccurs="unbounded">
        <xs:element name="BorderComponent" type="BorderComponentType" />
        <xs:element name="ImageComponent" type="ImageComponentType" />
        <xs:element name="TextComponent" type="TextComponentType" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="name" use="required" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="SectionType">
    <xs:attribute name="section" use="required" type="xs:string" />
    <xs:attribute name="color" use="optional" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="LayerType">
    <xs:sequence>
      <xs:element name="Section" maxOccurs="unbounded" minOccurs="1" type="SectionType" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="StateImageryType">
    <xs:sequence>
      <xs:element name="Layer" type="LayerType" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" use="required" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="VisualType">
    <xs:sequence minOccurs="0">
      <xs:choice maxOccurs="unbounded">
        <xs:element name="ImagerySection" type="ImagerySectionType" />
        <xs:element name="StateImagery" type="StateImageryType" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="AbsDimensionType">
    <xs:attribute name="x" use="optional" type="xs:decimal" />
    <xs:attribute name="y" use="optional" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="SizeType">
    <xs:sequence>
      <xs:element name="AbsDimension" type="AbsDimensionType" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="PositionType">
    <xs:sequence>
      <xs:element name="AbsDimension" type="AbsDimensionType" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="AnchorType">
    <xs:attribute name="point" use="required" type="AnchorPointType" />
    <xs:attribute name="relativePoint" use="optional" type="AnchorPointType" />
    <xs:attribute name="relativeTo" use="optional" type="xs:string" />
    <xs:attribute name="offset" use="optional" type="xs:decimal" />
  </xs:complexType>

  <xs:complexType name="AreaType">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Size" type="SizeType" />
        <xs:element name="Position" type="PositionType" />
        <xs:element name="Anchor" type="AnchorType" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="EventsType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:any processContents="lax" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ScriptsType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="OnClick" type="ScriptBlockType" />
      <xs:element name="OnLoad" type="ScriptBlockType" />
      <xs:element name="OnUpdate" type="ScriptBlockType" />
      <xs:element name="OnTabPressed" type="ScriptBlockType" />
      <xs:element name="OnEnterPressed" type="ScriptBlockType" />
      <xs:element name="OnSpacePressed" type="ScriptBlockType" />
      <xs:element name="OnEscapePressed" type="ScriptBlockType" />
      <xs:element name="OnShow" type="ScriptBlockType" />
      <xs:element name="OnHide" type="ScriptBlockType" />
      <xs:element name="OnEnter" type="ScriptBlockType" />
      <xs:element name="OnLeave" type="ScriptBlockType" />
      <xs:element name="OnDrag" type="ScriptBlockType" />
      <xs:element name="OnDrop" type="ScriptBlockType" />
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="FrameType">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Property" type="PropertyType" />
        <xs:element name="Visual" type="VisualType" />
        <xs:element name="Area" type="AreaType" />
        <xs:element name="Events" type="EventsType" />
        <xs:element name="Scripts" type="ScriptsType" />
        <xs:element name="Frame" type="FrameType" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="type" type="xs:string" use="optional" />
    <xs:attribute name="renderer" type="FrameRendererType" use="optional" />
    <xs:attribute name="inherits" type="xs:string" use="optional" />
    <xs:attribute name="parent" type="xs:string" use="optional" />
    <xs:attribute name="setAllPoints" type="xs:boolean" use="optional" />
    <xs:attribute name="id" type="xs:int" use="optional" />
  </xs:complexType>

  <xs:element name="Frame" type="FrameType" />

  <xs:element name="UiLayout">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Script" minOccurs="0" maxOccurs="unbounded" type="ScriptFileType" />
        <xs:element name="Font" minOccurs="0" maxOccurs="unbounded" type="FontType" />
        <xs:element ref="Frame" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Kyoril/mmo-data/Interface/GameUI/TalentFrame.xml
<?xml version="1.0" ?>
<UiLayout xmlns="http://www.w3schools.com/Ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com/Ui.xsd file:///F:/mmo/data/client/Interface/Ui.xsd">
	<Script file="TalentFrame.lua" />

	<Font name="TalentTabFont" file="Fonts/FRIZQT__.TTF" size="20" outline="0" shadowX="1.0" shadowY="1.0" />
	<Font name="TalentRankFont" file="Fonts/FRIZQT__.TTF" size="15" outline="1" shadowX="0.5" shadowY="0.5" />

	<Frame name="TalentFrameTabButtonTemplate" type="Button" renderer="CheckboxRenderer">
		<Property name="Font" value="TalentTabFont" />
		<Property name="Checkable" value="true" />
		<Visual>
			<ImagerySection name="NormalFrame"><BorderComponent texture="Interface/GameUI/fg4_buttonSmall1_Down_result.htex" borderSize="25" /></ImagerySection>
			<ImagerySection name="HoverFrame"><BorderComponent texture="Interface/GameUI/fg4_buttonSmall1_Up_result.htex" borderSize="25" /></ImagerySection>
			<ImagerySection name="SelectedFrame">
				<BorderComponent texture="Interface/GameUI/fg4_buttonSmall1_Over_result.htex" borderSize="25" />
				<BorderComponent texture="Interface/GameUI/fg4_borders_insetBlackSmall.htex" borderSize="8"><Area><Inset all="5" /></Area></BorderComponent>
			</ImagerySection>
			<ImagerySection name="Caption"><TextComponent color="FFB9A26A" horzAlign="CENTER" vertAlign="CENTER" /></ImagerySection>
			<ImagerySection name="CaptionActive"><TextComponent color="FFFFFFFF" horzAlign="CENTER" vertAlign="CENTER" /></ImagerySection>
			<StateImagery name="Normal"><Layer><Section section="NormalFrame" /><Section section="Caption" /></Layer></StateImagery>
			<StateImagery name="Hovered"><Layer><Section section="HoverFrame" /><Section section="CaptionActive" /></Layer></StateImagery>
			<StateImagery name="Pushed"><Layer><Section section="SelectedFrame" /><Section section="CaptionActive" /></Layer></StateImagery>
			<StateImagery name="NormalChecked"><Layer><Section section="SelectedFrame" /><Section section="CaptionActive" /></Layer></StateImagery>
			<StateImagery name="HoveredChecked"><Layer><Section section="SelectedFrame" /><Section section="CaptionActive" /></Layer></StateImagery>
			<StateImagery name="PushedChecked"><Layer><Section section="SelectedFrame" /><Section section="CaptionActive" /></Layer></StateImagery>
		</Visual>
		<Area><Size><AbsDimension x="360" y="76" /></Size></Area>
	</Frame>

	<Frame name="TalentFrameTalentTemplate" type="Button" renderer="CheckboxRenderer">
		<Property name="Icon" />
		<Property name="IconTint" value="FFFFFFFF" />
		<Property name="GlowTint" value="00000000" />
		<Property name="Checkable" value="true" />
		<Visual>
			<ImagerySection name="Glow"><ImageComponent texture="Interface/GlueUI/GlowYellow.htex" tint="$GlowTint"><Area><Inset all="-16" /></Area></ImageComponent></ImagerySection>
			<ImagerySection name="NormalFrame"><BorderComponent texture="Interface/BW_ButtonSmall_Up.htex" borderSize="30" /></ImagerySection>
			<ImagerySection name="HoverFrame"><BorderComponent texture="Interface/BW_ButtonSmall_Over.htex" borderSize="30" /></ImagerySection>
			<ImagerySection name="PushedFrame"><BorderComponent texture="Interface/BW_ButtonSmall_Down.htex" borderSize="30" /></ImagerySection>
			<ImagerySection name="DisabledFrame"><BorderComponent texture="Interface/BW_ButtonSmall_Up.htex" borderSize="30" /></ImagerySection>
			<ImagerySection name="Icon"><ImageComponent tint="$IconTint"><Area><Inset all="16" /></Area><PropertyValue property="Icon" /></ImageComponent></ImagerySection>
			<ImagerySection name="DisabledIcon"><ImageComponent tint="FF676B72"><Area><Inset all="16" /></Area><PropertyValue property="Icon" /></ImageComponent></ImagerySection>
			<StateImagery name="Normal"><Layer><Section section="Glow" /><Section section="NormalFrame" /><Section section="Icon" /></Layer></StateImagery>
			<StateImagery name="Hovered"><Layer><Section section="Glow" /><Section section="HoverFrame" /><Section section="Icon" /></Layer></StateImagery>
			<StateImagery name="Pushed"><Layer><Section section="Glow" /><Section section="PushedFrame" /><Section section="Icon" /></Layer></StateImagery>
			<StateImagery name="NormalChecked"><Layer><Section section="HoverFrame" /><Section section="Icon" /></Layer></StateImagery>
			<StateImagery name="HoveredChecked"><Layer><Section section="PushedFrame" /><Section section="Icon" /></Layer></StateImagery>
			<StateImagery name="PushedChecked"><Layer><Section section="PushedFrame" /><Section section="Icon" /></Layer></StateImagery>
			<StateImagery name="Disabled"><Layer><Section section="DisabledFrame" /><Section section="DisabledIcon" /></Layer></StateImagery>
		</Visual>
		<Area><Size><AbsDimension x="128" y="128" /></Size></Area>
		<Frame name="Rank" renderer="DefaultRenderer">
			<Property name="Font" value="TalentRankFont" />
			<Property name="TextColor" value="FFFFFFFF" />
			<Property name="Clickable" value="false" />
			<Visual>
				<ImagerySection name="Background"><BorderComponent texture="Interface/GameUI/fg4_borders_insetBlackSmall.htex" borderSize="4" tint="EE000000" /><TextComponent color="$TextColor" horzAlign="CENTER" vertAlign="CENTER" /></ImagerySection>
				<StateImagery name="Enabled"><Layer><Section section="Background" /></Layer></StateImagery>
			</Visual>
			<Area><Size><AbsDimension x="48" y="30" /></Size><Anchor point="BOTTOM" offset="-2" /><Anchor point="RIGHT" offset="-2" /></Area>
		</Frame>
	</Frame>

	<Frame name="TalentFrameLineTemplate" type="Line">
		<Property name="Texture" value="Textures/Character/T_EV_BlankWhite_01.htex" />
		<Property name="Color" value="FF4A5360" />
		<Property name="Thickness" value="5" />
		<Property name="Clickable" value="false" />
		<Property name="ClippedByParent" value="false" />
	</Frame>

	<Frame name="TalentFrame" renderer="DefaultRenderer" parent="GameParent">
		<Property name="Visible" value="false" />
		<Visual>
			<ImagerySection name="Background"><BorderComponent texture="Interface/GameUI/fg4_borders_simple.htex" borderSize="250" /></ImagerySection>
			<StateImagery name="Enabled"><Layer><Section section="Background" /></Layer></StateImagery>
		</Visual>
		<Area>
			<Size><AbsDimension x="2700" y="1720" /></Size>
			<Anchor point="H_CENTER" />
			<Anchor point="V_CENTER" />
		</Area>

		<Frame name="TalentFrameTitleBar" inherits="TitleBar">
			<Property name="Text" value="TALENTS" />
			<Area><Anchor point="TOP" offset="24" /><Anchor point="LEFT" offset="24" /><Anchor point="RIGHT" offset="-24" /></Area>
		</Frame>

		<Frame name="TalentFrameTabContainer">
			<Area><Anchor point="TOP" relativePoint="BOTTOM" relativeTo="TalentFrameTitleBar" offset="18" /><Anchor point="LEFT" offset="70" /><Anchor point="RIGHT" offset="-70" /><Size><AbsDimension y="82" /></Size></Area>
		</Frame>

		<Frame name="TalentFrameCanvasViewport" renderer="DefaultRenderer">
			<Property name="Focusable" value="true" />
			<Property name="Background" value="Interface/GameUI/TalentFrameBackground.htex" />
			<Visual>
				<ImagerySection name="Canvas">
					<ImageComponent tint="FFB7C0CB"><Area><Inset all="12" /></Area><PropertyValue property="Background" /></ImageComponent>
					<BorderComponent texture="Interface/GameUI/fg4_borders_01_19.htex" borderSize="25" />
				</ImagerySection>
				<StateImagery name="Enabled"><Layer><Section section="Canvas" /></Layer></StateImagery>
			</Visual>
			<Area><Anchor point="TOP" relativePoint="BOTTOM" relativeTo="TalentFrameTabContainer" offset="12" /><Anchor point="LEFT" offset="54" /><Anchor point="RIGHT" offset="-54" /><Anchor point="BOTTOM" offset="-150" /></Area>
			<Frame name="TalentFrameCanvasContent">
				<Property name="ClippedByParent" value="true" />
				<Property name="Clickable" value="false" />
				<Area><Size><AbsDimension x="1600" y="1200" /></Size><Anchor point="TOP" offset="0" /><Anchor point="LEFT" offset="0" /></Area>
			</Frame>
		</Frame>

		<Frame name="TalentFrameZoomOut" inherits="GlueButton"><Property name="Text" value="-" /><Area><Anchor point="BOTTOM" offset="-52" /><Anchor point="LEFT" offset="76" /><Size><AbsDimension x="88" y="70" /></Size></Area></Frame>
		<Frame name="TalentFrameZoomReset" inherits="GlueButton"><Property name="Text" value="TALENT_RESET_VIEW" /><Area><Anchor point="BOTTOM" offset="-52" /><Anchor point="LEFT" relativePoint="RIGHT" relativeTo="TalentFrameZoomOut" offset="8" /><Size><AbsDimension x="260" y="70" /></Size></Area></Frame>
		<Frame name="TalentFrameZoomIn" inherits="GlueButton"><Property name="Text" value="+" /><Area><Anchor point="BOTTOM" offset="-52" /><Anchor point="LEFT" relativePoint="RIGHT" relativeTo="TalentFrameZoomReset" offset="8" /><Size><AbsDimension x="88" y="70" /></Size></Area></Frame>

		<Frame name="TalentFramePointsText" inherits="TextSmall">
			<Property name="HorzAlign" value="CENTER" />
			<Property name="TextColor" value="FFFFD100" />
			<Area><Anchor point="BOTTOM" offset="-64" /><Anchor point="LEFT" offset="700" /><Anchor point="RIGHT" offset="-700" /><Size><AbsDimension y="56" /></Size></Area>
		</Frame>

		<Scripts>
			<OnLoad>return function(this) TalentFrame_OnLoad(this) end</OnLoad>
			<OnShow>return function(this) TalentFrame_OnShow(this) end</OnShow>
		</Scripts>
	</Frame>
</UiLayout>

=== Kyoril/mmo-data/Interface/GameUI/TargetFrame.xml
<?xml version="1.0" ?>
<UiLayout xmlns="http://www.w3schools.com/Ui" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com/Ui.xsd file:///F:/mmo/data/client/Interface/Ui.xsd">
	<Script file="TargetFrame.lua" />

    <Frame name="TargetFrame" parent="GameParent" renderer="DefaultRenderer">
		<Area>
			<Size>
				<AbsDimension x="512" y="174" />
				<Anchor point="LEFT" relativePoint="H_CENTER" offset="384" />
				<Anchor point="TOP" relativeTo="PlayerFrame" />
			</Size>
		</Area>

		<Visual>
			<ImagerySection name="Background">
                <BorderComponent texture="Interface/GameUI/fg4_gradientBlackCircle2.htex" borderSize="31" tint="81FFFFFF" />
            </ImagerySection>
            <StateImagery name="Enabled">
                <Layer>
                    <Section section="Background" />
                </Layer>
            </StateImagery>
            <StateImagery name="Disabled">
                <Layer>
                    <Section section="Background" />
                </Layer>
            </StateImagery>
		</Visual>

		<Frame name="TargetPortrait" renderer="DefaultRenderer">
			<Area>
				<Anchor point="TOP" offset="5" />
				<Anchor point="RIGHT" offset="-5" />
				<Size><AbsDimension x="128" y="128" /></Size>
			</Area>

			<Visual>
				<ImagerySection name="Background">
					<BorderComponent texture="Interface/GameUI/fg4_slotBrownRound1_result.htex" borderSize="36" tint="FFFFFFFF" />
				</ImagerySection>
				<StateImagery name="Enabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Disabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
			</Visual>

			<Frame name="TargetPortraitModel" type="UnitModel" renderer="ModelRenderer">
				<Property name="Animation" value="Idle" />
				<Property name="Yaw" value="-90" />
				<Property name="Zoom" value="0.55" />
				<Property name="OffsetY" value="1.7" />

				<Area>
					<Anchor point="TOP" offset="16" />
					<Anchor point="LEFT" offset="16" />
					<Anchor point="RIGHT" offset="-16" />
					<Anchor point="BOTTOM" offset="-16" />
				</Area>
			</Frame>

			<Frame name="TargetPortraitLevel" renderer="DefaultRenderer">
				<Property name="Font" value="DefaultSmall" />
				<Property name="TextColor" value="FFFFFFFF" />
				
				<Visual>
					<ImagerySection name="Background">
						<ImageComponent texture="Interface/GameUI/fg4_progressbar1.htex" tiling="NONE" tint="FFFF0909" />
						<TextComponent color="$TextColor" horzAlign="CENTER" vertAlign="CENTER" />
					</ImagerySection>
					<StateImagery name="Enabled">
						<Layer>
							<Section section="Background" />
						</Layer>
					</StateImagery>
					<StateImagery name="Disabled">
						<Layer>
							<Section section="Background" />
						</Layer>
					</StateImagery>
				</Visual>

				<Area>
					<Anchor point="H_CENTER" />
					<Anchor point="BOTTOM" offset="24" />
					<Size><AbsDimension x="72" y="48" /></Size>
				</Area>
			</Frame>
		</Frame>

		<Frame name="TargetName" inherits="TextSmall">
			<Property name="Font" value="DefaultSmallOutline" />
			<Property name="HorzAlign" value="CENTER" />

            <Area>
                <Anchor point="LEFT" offset="10" />
                <Anchor point="RIGHT" relativePoint="LEFT" relativeTo="TargetPortrait" offset="-10" />
                <Anchor point="TOP" offset="10" />
                <Size><AbsDimension y="42" /></Size>
            </Area>
		</Frame>

		<Frame name="TargetHealthBar" type="ProgressBar">
			<Property name="Progress" value="0.12783" />
			<Property name="Font" value="DefaultSmall" />

			<Area>
                <Anchor point="LEFT" offset="10" />
                <Anchor point="RIGHT" relativePoint="LEFT" relativeTo="TargetPortrait" offset="-10" />
				<Anchor point="TOP" relativeTo="TargetName" relativePoint="BOTTOM" />
				<Size><AbsDimension y="70" /></Size>
			</Area>

			<Visual>
				<ImagerySection name="Caption">
					<TextComponent color="FFFFFFFF" horzAlign="CENTER" vertAlign="CENTER" />
				</ImagerySection>
				<ImagerySection name="Background">
					<BorderComponent texture="Interface/fg4_borders_01_33.htex" borderSize="5" />
				</ImagerySection>
				<ImagerySection name="Border">
					<BorderComponent texture="Interface/GameUI/fg4_borders_insetBlackSmall.htex" borderSize="11" />
				</ImagerySection>
				<ImagerySection name="Progress">
					<ImageComponent texture="Interface/fg4_gradientWhiteV1_result.htex" tiling="HORZ" tint="FF00FF00">
						<Area><Inset all="8" /></Area>
					</ImageComponent>
				</ImagerySection>

				<StateImagery name="Enabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Disabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Progress">
					<Layer>
						<Section section="Progress" />
					</Layer>
				</StateImagery>
				<StateImagery name="Overlay">
					<Layer>
						<Section section="Border" />
						<Section section="Caption" />
					</Layer>
				</StateImagery>
			</Visual>
		</Frame>

		<Frame name="TargetManaBar" type="ProgressBar">
			<Property name="Progress" value="0.12783" />
			<Property name="Font" value="DefaultSmall" />

			<Area>
                <Anchor point="LEFT" offset="10" />
                <Anchor point="RIGHT" relativePoint="LEFT" relativeTo="TargetPortrait" offset="-10" />
				<Anchor point="TOP" relativePoint="BOTTOM" relativeTo="TargetHealthBar" />
				<Size><AbsDimension y="40" /></Size>
			</Area>

			<Visual>
				<ImagerySection name="Caption">
					<TextComponent color="FFFFFFFF" horzAlign="CENTER" vertAlign="CENTER" />
				</ImagerySection>
				<ImagerySection name="Background">
					<BorderComponent texture="Interface/fg4_borders_01_33.htex" borderSize="5" />
				</ImagerySection>
				<ImagerySection name="Border">
					<BorderComponent texture="Interface/GameUI/fg4_borders_insetBlackSmall.htex" borderSize="11" />
				</ImagerySection>
				<ImagerySection name="Progress">
					<ImageComponent texture="Interface/fg4_gradientWhiteV1_result.htex" tiling="HORZ" tint="FF0000FF">
						<Area><Inset all="8" /></Area>
					</ImageComponent>
				</ImagerySection>

				<StateImagery name="Enabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Disabled">
					<Layer>
						<Section section="Background" />
					</Layer>
				</StateImagery>
				<StateImagery name="Progress">
					<Layer>
						<Section section="Progress" />
					</Layer>
				</StateImagery>
				<StateImagery name="Overlay">
					<Layer>
						<Section section="Border" />
						<Section section="Caption" />
					</Layer>
				</StateImagery>
			</Visual>
		</Frame>

        <Frame name="TargetAuraButton1" inherits="AuraBarButtonTemplate" id="1">
            <Area>
                <Anchor point="LEFT" offset="0" />
                <Anchor point="TOP" relativePoint="BOTTOM" offset="0" />
				<Size><AbsDimension x="96" y="96" /></Size>
            </Area>
        </Frame>
        
        <Frame name="TargetAuraButton2" inherits="AuraBarButtonTemplate" id="2">
            <Area>
                <Anchor point="LEFT" relativeTo="TargetAuraButton1" relativePoint="RIGHT" offset="0" />
                <Anchor point="TOP" relativeTo="TargetAuraButton1" />
				<Size><AbsDimension x="96" y="96" /></Size>
            </Area>
        </Frame>
        
        <Frame name="TargetAuraButton3" inherits="AuraBarButtonTemplate" id="3">
            <Area>
                <Anchor point="LEFT" relativeTo="TargetAuraButton2" relativePoint="RIGHT" offset="0" />
                <Anchor point="TOP" relativeTo="TargetAuraButton1" />
				<Size><AbsDimension x="96" y="96" /></Size>
            </Area>
        </Frame>
        
        <Frame name="TargetAuraButton4" inherits="AuraBarButtonTemplate" id="4">
            <Area>
                <Anchor point="LEFT" relativeTo="TargetAuraButton3" relativePoint="RIGHT" offset="0" />
                <Anchor point="TOP" relativeTo="TargetAuraButton1" />
				<Size><AbsDimension x="96" y="96" /></Size>
            </Area>
        </Frame>
        
        <Frame name="TargetAuraButton5" inherits="AuraBarButtonTemplate" id="5">
            <Area>
                <Anchor point="LEFT" relativeTo="TargetAuraButton4" relativePoint="RIGHT" offset="0" />
                <Anchor point="TOP" relativeTo="TargetAuraButton1" />
				<Size><AbsDimension x="96" y="96" /></Size>
            </Area>
        </Frame>

		<Frame name="TargetFrameClick" setAllPoints="true">
			<Scripts>
				<OnClick>
					return function(self, button)
						local pos = GetCursorPosition()
						TargetFrame_OnClick(TargetFrame, button, pos.x, pos.y)
					end
				</OnClick>
			</Scripts>
		</Frame>

		<Scripts>
			<OnLoad>
				return function(this)
					TargetFrame_OnLoad();
				end
			</OnLoad>
		</Scripts>
    </Frame>
</UiLayout>
